/* $Id: asm.h,v 1.2 2001/05/31 21:32:21 marvin Exp $
 *
 * Stuff used in asm code mainly.
 */

#ifndef __INCLUDE_SYS_ASM_H__
#define __INCLUDE_SYS_ASM_H__

#define MEM_GDTSEG 0
#define MEM_IDTSEG 0x1000
#define MEM_PARMSEG 0x1080

#define NULL_SELECTOR 0 << 3
#define KERNEL_CODE_SELECTOR 1 << 3
#define KERNEL_DATA_SELECTOR 2 << 3
#define KERNEL_STACK_SELECTOR 2 << 3

/*
 * Linear addresses
 */
#define PHYSICAL_LINEAR_ADDRESS (0xc0000000)
#define KERNEL_LINEAR_ADDRESS (PHYSICAL_LINEAR_ADDRESS+KERNEL_PHYSICAL_ADDRESS)
#define SCREEN_LINEAR_ADDRESS (PHYSICAL_LINEAR_ADDRESS+SCREEN_PHYSICAL_ADDRESS)
#define INIT_KSTACK_LINEAR_ADDRESS (PHYSICAL_LINEAR_ADDRESS + 0xfffe)
#define GDT_LINEAR_ADDRESS (PHYSICAL_LINEAR_ADDRESS)
#define IDT_LINEAR_ADDRESS (PHYSICAL_LINEAR_ADDRESS + 0x10000)

#define BOOTSEG   0x07C0
#define INITSEG   0x1000

#define KERNEL_LOADER_SEG 0x8000
#define KERNEL_SEG     0x3000

#define KERNEL_PHYSICAL_ADDRESS        (0x00030000)
#define SCREEN_PHYSICAL_ADDRESS        (0x000b8000)
#define PAGEDIRECTORY_PHYSICAL_ADDRESS (0x00011000)

#define RAMDRIVE_SEG 0x7000

#define STACKSEG  0x9000

#define PAGETABLE300_ADDRESS 0x12000
#endif
